name: linter

on:
  push:
    branches:
      - main
      - master
jobs:
  lint_and_install:
    name: Run Linting Checks and Installation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.1

      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

      - name: Install dependencies
        run: make install

      - name: Makefile lint
        run: make lint
